[package]
name = "cli"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
simulation = { workspace = true }
compute_core = { workspace = true }
data_processor = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true}
pollster = { workspace = true}
